### ISSUE TITLE
Make it possible to define LvGL config in a higher level format

### ISSUE THREAD

**Issue by rafaelcaricio** [rafaelcaricio/lvgl-rs#11]
Would be nice to define library properties in a high level format than `lv_conf.h` file. Possibly, a `lv_conf.toml` would be a better approach. We could do validations and consistency checks at build time (`build.rs`) and generate the final `lv_conf.h` dynamically right before compilation.

An example content of how the `lv_conf.toml` could look like:
```toml
# ====================
#  Graphical settings
# ====================
[graphical]
# Maximal horizontal and vertical resolution to support by the library.
hor_res_max=480
ver_res_max=320
```
Users would be required only to define what differs from the default values. This also makes it easier to spot differences.
